service:
  name: email-service
provider:
  name: aws
  runtime: nodejs12.x
  stage: '${opt:stage,''dev''}'
  memorySize: 256
  timeout: 15
  region: us-east-1
  stackName: ${self:service.name}-${self:provider.stage}
  environment:
    DEPLOYED_ENV: ${self:provider.stage}
    SES_NOTIFICATION_CONFIGURATION_SET: !Ref EmailServiceNotificationConfigurationSet
    RECORD_TABLE: !Ref EmailServiceTable
    RECORD_LIFECYCLE_EXPIRATION_DAYS: !Ref EmailServiceRecordLifeCycleExpirationParameter
    API_BASE_URL: !Join ['', [ 'https://', !Ref ApiGatewayRestApi, '.execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}' ] ]
functions:
  send:
    handler: lambdas/send.handler
    role: EmailServiceLambdaRole
    reservedConcurrency: 100
    events:
      - http:
          path: /send
          method: post
          async: false
  notification:
    handler: lambdas/notification.handler
    role: EmailServiceLambdaRole
    reservedConcurrency: 100
    events:
      - sqs:
          batchSize: 1
          arn:
            !GetAtt EmailServiceStatusNotificationQueue.Arn
resources:
  ######################################
  ##### Stack Customizable Params ######
  ######################################
  Parameters:
    EmailServiceRecordLifeCycleExpirationParameter:
      Type: String
      Default: 180
      Description: Number of days before email records in record table expire and are automatically removed.
    EmailServiceStatusNotificationQueueRetentionPeriodParameter:
      Type: String
      Default: 604800
      Description: Number of seconds before item in notification queue expires
    EmailServiceStatusNotificationDLQRetentionPeriodParameter:
      Type: String
      Default: 1209600
      Description: Number of seconds before item in notification dead letter queue expires

  ####################################
  ########## Stack Resources #########
  ####################################
  Resources:
    ############################
    ########## Common ##########
    ############################
    EmailServiceLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ${self:service.name}-${self:provider.stage}-lambda-role-policy
            PolicyDocument:
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: '*'
                - Effect: Allow
                  Action:
                    - sns:Publish
                  Resource: '*'
                - Effect: Allow
                  Action:
                    - ses:SendEmail
                    - ses:SendRawEmail
                  Resource:
                    - '*'
                - Effect: Allow
                  Action:
                    - dynamodb:Query
                    - dynamodb:Scan
                    - dynamodb:GetItem
                    - dynamodb:PutItem
                    - dynamodb:UpdateItem
                    - dynamodb:DeleteItem
                  Resource: !GetAtt EmailServiceTable.Arn
                - Effect: Allow
                  Action:
                    - sqs:ReceiveMessage
                    - sqs:DeleteMessage
                    - sqs:GetQueueAttributes
                    - sqs:ChangeMessageVisibility
                  Resource:
                    - !GetAtt EmailServiceStatusNotificationQueue.Arn
    EmailServiceTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: emailServiceId
            AttributeType: S
        KeySchema:
          - AttributeName: emailServiceId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TimeToLiveSpecification:
          AttributeName: lifecycleExpiresAt
          Enabled: true

    ############################
    ## Delivery Notifications ##
    ############################
    EmailServiceNotificationConfigurationSet:
      Type: AWS::SES::ConfigurationSet
      Properties:
        Name: ${self:service.name}-${self:provider.stage}-notification-configuration-set
    EmailServiceStatusNotificationTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:service.name}-${self:provider.stage}-notification
    EmailServiceStatusNotificationTopicSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref EmailServiceStatusNotificationTopic
        Endpoint: !GetAtt
          - EmailServiceStatusNotificationQueue
          - Arn
        Protocol: sqs
        RawMessageDelivery: true
    EmailServiceStatusNotificationQueue:
      Type: AWS::SQS::Queue
      Properties:
        MessageRetentionPeriod: !Ref EmailServiceStatusNotificationQueueRetentionPeriodParameter
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt EmailServiceStatusNotificationDLQ.Arn
          maxReceiveCount: 3
    EmailServiceStatusNotificationDLQ:
      Type: AWS::SQS::Queue
      Properties:
        MessageRetentionPeriod: !Ref EmailServiceStatusNotificationDLQRetentionPeriodParameter
    EmailServiceStatusNotificationQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: sns.amazonaws.com
              Resource: !GetAtt EmailServiceStatusNotificationQueue.Arn
              Action: SQS:SendMessage
              Condition:
                ArnEquals:
                  "aws:SourceArn": !Ref EmailServiceStatusNotificationTopic
        Queues:
          - Ref: EmailServiceStatusNotificationQueue

  ##################################
  ########## Stack Outputs #########
  ##################################
  Outputs:
    SendEmailEndpoint:
      Description: "Send Email Endpoint"
      Value:
        !Join ['', [ 'https://', !Ref ApiGatewayRestApi, '.execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}', '/send' ] ]