service:
  name: email-service
provider:
  name: aws
  runtime: nodejs12.x
  stage: '${opt:stage,''dev''}'
  memorySize: 256
  timeout: 15
  region: us-east-1
  stackName: ${self:service.name}-${self:provider.stage}
  environment:
    DEPLOYED_ENV: ${self:provider.stage}
    MEDIA_BUCKET: !Ref EmailServiceMediaBucket
    RECORD_TABLE: !Ref EmailServiceTable
    SES_NOTIFICATION_CONFIGURATION_SET: !Ref EmailServiceNotificationConfigurationSet
    API_BASE_URL: !Join ['', [ 'https://', !Ref ApiGatewayRestApi, '.execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}' ] ]
functions:
  send:
    handler: lambdas/send.handler
    role: EmailServiceLambdaRole
    reservedConcurrency: 100
    events:
      - http:
          path: /send
          method: post
          async: false
  notification:
    handler: lambdas/notification.handler
    role: EmailServiceLambdaRole
    reservedConcurrency: 100
    events:
      - sqs:
          batchSize: 1
          arn:
            !GetAtt EmailServiceNotificationDeliveryQueue.Arn
resources:
  Resources:
    ############################
    ########## Common ##########
    ############################
    EmailServiceDefaultFromParameter:
      Type: AWS::SSM::Parameter
      Properties:
        Name: !Sub /${self:service.name}/${self:provider.stage}/DEFAULT_FROM_ADDRESS
        Type: String
        Value: 'noreply@eztouch-menu.com'
    EmailServiceDefaultFromName:
      Type: AWS::SSM::Parameter
      Properties:
        Name: !Sub /${self:service.name}/${self:provider.stage}/DEFAULT_FROM_NAME
        Type: String
        Value: 'EZTouch Menu'
    EmailServiceLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ${self:service.name}-${self:provider.stage}-lambda-role-policy
            PolicyDocument:
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: '*'
                - Effect: Allow
                  Action:
                    - s3:GetObject
                    - s3:PutObject
                  Resource: !Join ['', [ 'arn:aws:s3:::', !Ref EmailServiceMediaBucket, '/*' ] ]
                - Effect: Allow
                  Action:
                    - sns:Publish
                  Resource: '*'
                - Effect: Allow
                  Action:
                    - ses:SendEmail
                    - ses:SendRawEmail
                  Resource:
                    - '*'
                - Effect: Allow
                  Action:
                    - dynamodb:Query
                    - dynamodb:Scan
                    - dynamodb:GetItem
                    - dynamodb:PutItem
                    - dynamodb:UpdateItem
                    - dynamodb:DeleteItem
                  Resource: !GetAtt EmailServiceTable.Arn
                - Effect: Allow
                  Action:
                    - sqs:ReceiveMessage
                    - sqs:DeleteMessage
                    - sqs:GetQueueAttributes
                    - sqs:ChangeMessageVisibility
                  Resource:
                    - !GetAtt EmailServiceNotificationDeliveryQueue.Arn
    EmailServiceTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: emailServiceId
            AttributeType: S
        KeySchema:
          - AttributeName: emailServiceId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TimeToLiveSpecification:
          AttributeName: lifecycleExpiresAt
          Enabled: true
    EmailServiceMediaBucket:
      Type: AWS::S3::Bucket

    ############################
    ## Delivery Notifications ##
    ############################
    EmailServiceNotificationConfigurationSet:
      Type: AWS::SES::ConfigurationSet
      Properties:
        Name: ${self:service.name}-${self:provider.stage}-notification-configuration-set

    EmailServiceNotificationDeliveryTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:service.name}-${self:provider.stage}-notification-delivery
    EmailServiceNotificationDeliveryTopicSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref EmailServiceNotificationDeliveryTopic
        Endpoint: !GetAtt
          - EmailServiceNotificationDeliveryQueue
          - Arn
        Protocol: sqs
        RawMessageDelivery: true
    EmailServiceNotificationDeliveryQueue:
      Type: AWS::SQS::Queue
      Properties:
        MessageRetentionPeriod: 604800
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt EmailServiceNotificationDeliveryDLQ.Arn
          maxReceiveCount: 3
    EmailServiceNotificationDeliveryDLQ:
      Type: AWS::SQS::Queue
      Properties:
        MessageRetentionPeriod: 1209600
    EmailServiceNotificationDeliveryQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: sns.amazonaws.com
              Resource: !GetAtt EmailServiceNotificationDeliveryQueue.Arn
              Action: SQS:SendMessage
              Condition:
                ArnEquals:
                  "aws:SourceArn": !Ref EmailServiceNotificationDeliveryTopic
        Queues:
          - Ref: EmailServiceNotificationDeliveryQueue

  ##################################
  ########## Stack Outputs #########
  ##################################
  Outputs:
    SendEmailEndpoint:
      Description: "Send Email Endpoint"
      Value:
        !Join ['', [ 'https://', !Ref ApiGatewayRestApi, '.execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}', '/send' ] ]