POST https://${API_ID}.execute-api.us-east-1.amazonaws.com/dev/send
Content-Type: application/json

{
  "from": "noreply@example.com",
  "subject": "This is the subject of the email",
  "content": {
    "text": "This is the plain text email content",
    "html": "<html><body><h1>This is the html email content</h1></body></html>"
  },
  "recipients": {
    "to": [
      {
        "email": "jim@example.com",
        "name": "Jim Halpert"
      }
    ],
    "cc": [
      {
        "email": "stanley@example.com",
        "name": "Stanley Hudson"
      }
    ],
    "bcc": [
      {
        "email": "dwight@example.com",
        "name": "Dwight Schrute"
      }
    ]
  }
}

